language: ruby
cache: bundler

before_install:
  - sudo apt-get install -y webp libopenjp2-7 libopenjp2-tools
  - gem update --system
  - gem install bundler

script:
  - bundle exec rake test
  - bundle exec rake rubocop
