# Sample Jekyll Picture Tag settings
# Note that all of these settings have sensible defaults. Don't just copy-paste
# this into your _config.yml!
picture:
  source: assets/images/_fullsize
  output: generated 
  suppress_warnings: false
  ignore_missing_images: [development, test]
  cdn_url: cdn.example.com
  cdn_environments: production
